version: '3.8'

services:
  postgres:
    container_name: monopoly-postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/main/resources/docker/postgresql/:/docker-entrypoint-initdb.d/
